# Generated by Django 5.0.4 on 2024-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profileimg', models.ImageField(upload_to='img')),
                ('regdno', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
